#!/usr/bin/env python3
# Copyright 2026 George Kapellakis
# Licensed under the Apache License, Version 2.0
# See LICENSE file for details.
"""
Build script — compiles fast_copy into a standalone executable.

Usage:
  python build.py              # build CLI executable
  python build.py --clean      # clean build artifacts first

Output:
  dist/fast_copy       — CLI executable
"""

import os
import sys
import shutil
import platform
import importlib.util
import subprocess

# Optional cloud backends. When importable in the build environment they are
# bundled into the frozen binary (see cloud_collect_flags) so the standalone
# GUI/CLI — whose --fc-core engine runs inside the same embedded interpreter —
# can do s3://, az:// and gs:// transfers without a separate Python install.
# Maps the probe-import to the top packages PyInstaller must collect whole
# (these carry data files / metadata that import analysis alone would miss).
CLOUD_COLLECT = {
    "boto3": ["boto3", "botocore", "s3transfer"],
    "azure.storage.blob": ["azure.storage.blob", "azure.core"],
    "google.cloud.storage": ["google.cloud.storage", "google.cloud",
                             "google.api_core", "google.auth",
                             "google.resumable_media"],
    "smbclient": ["smbprotocol", "smbclient", "spnego", "pyasn1"],
}

# Shared libraries the bundle must NOT carry — the host has to provide them.
# Qt's xcb plugin builds its keymap through the host's libxkbcommon-x11, then
# reads it back through libxkbcommon — which the loader resolves to the bundled
# copy. When the two come from different releases their internal keymap structs
# disagree and Qt segfaults inside xkb_state_key_get_layout on the first X key
# event. Leaving them out keeps the host's matched pair intact.
HOST_LIBS = ("libxkbcommon.so", "libxkbcommon-x11.so")

GUI_SPEC_TEMPLATE = '''# -*- mode: python ; coding: utf-8 -*-
# Generated by build.py — do not edit by hand.
import os
from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = [], [], ['xxhash', 'paramiko']
for pkg in {pkgs!r}:
    _d, _b, _h = collect_all(pkg)
    datas += _d
    binaries += _b
    hiddenimports += _h

a = Analysis([{script!r}], binaries=binaries, datas=datas,
             hiddenimports=hiddenimports)

a.binaries = [b for b in a.binaries
              if not os.path.basename(b[0]).startswith({host_libs!r})]

pyz = PYZ(a.pure)
exe = EXE(pyz, a.scripts, a.binaries, a.datas, [],
          name={name!r}, debug=False, strip=False, upx=False,
          runtime_tmpdir=None, console=False, icon={icon!r})
'''


def install_deps():
    """Install build dependencies."""
    deps = {
        "pyinstaller": "PyInstaller",
        "xxhash": "xxhash",
        "paramiko": "paramiko",
        "PySide6": "PySide6",
    }
    for pip_name, import_name in deps.items():
        try:
            __import__(import_name)
            print(f"  OK: {pip_name}")
        except ImportError:
            print(f"  Installing {pip_name}...")
            try:
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install", pip_name, "--quiet",
                    "--disable-pip-version-check",
                ])
            except subprocess.CalledProcessError:
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install", pip_name, "--quiet",
                    "--disable-pip-version-check", "--break-system-packages",
                ])
    # pywin32 is Windows-only and required for NTFS owner/ACL preservation;
    # without it the ACL copy silently no-ops in the frozen binary. Installed
    # from requirements-win.txt (same file CI uses) so the version pin has a
    # single source of truth.
    if platform.system() == "Windows":
        try:
            __import__("win32security")
            print("  OK: pywin32")
        except ImportError:
            print("  Installing pywin32 (requirements-win.txt)...")
            try:
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install", "-r",
                    "requirements-win.txt", "--quiet",
                    "--disable-pip-version-check",
                ])
            except subprocess.CalledProcessError:
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install", "-r",
                    "requirements-win.txt", "--quiet",
                    "--disable-pip-version-check", "--break-system-packages",
                ])
    # Optional cloud SDKs — best-effort so the binary ships with cloud support.
    # A failure here is non-fatal: the build proceeds and simply omits cloud.
    if os.path.exists("requirements-cloud.txt"):
        try:
            __import__("boto3")
            print("  OK: cloud SDKs (boto3/azure/gcs)")
        except ImportError:
            print("  Installing cloud SDKs (boto3/azure/gcs)...")
            for extra in ([], ["--break-system-packages"]):
                try:
                    subprocess.check_call([
                        sys.executable, "-m", "pip", "install", "-r",
                        "requirements-cloud.txt", "--quiet",
                        "--disable-pip-version-check", *extra,
                    ])
                    break
                except subprocess.CalledProcessError:
                    continue
            else:
                print("  WARN: cloud SDKs not installed — binary will omit "
                      "s3://, az:// and gs:// support")


def _cloud_packages():
    """The cloud SDK packages to collect whole, for whichever are importable."""
    collected, seen = [], set()
    for probe, pkgs in CLOUD_COLLECT.items():
        if importlib.util.find_spec(probe) is None:
            continue
        for pkg in pkgs:
            if pkg not in seen:
                seen.add(pkg)
                collected.append(pkg)
    return collected


def cloud_collect_flags():
    """`--collect-all` flags for whichever cloud SDKs are importable here."""
    return ["--collect-all=" + pkg for pkg in _cloud_packages()]


def _gui_spec_cmd(name, script, icon):
    """Build the Linux GUI through a generated .spec, so HOST_LIBS can be kept
    out of the bundle — the PyInstaller CLI offers no way to exclude a binary."""
    spec_path = f"{name}.spec"
    with open(spec_path, "w") as fh:
        fh.write(GUI_SPEC_TEMPLATE.format(
            pkgs=_cloud_packages(),
            script=os.path.abspath(script),
            name=name,
            host_libs=HOST_LIBS,
            icon=os.path.abspath(icon) if icon and os.path.exists(icon) else None,
        ))
    # Only build-time options are legal alongside a .spec; the makespec ones
    # (--onefile, --windowed, --noupx, --icon...) are baked into the spec above.
    return [sys.executable, "-m", "PyInstaller", "--clean", spec_path]


def build_target(name, script, windowed=False, icon=None):
    """Build a single target with PyInstaller.

    windowed=True builds a GUI app (no console window; a .app bundle on macOS).
    icon is a path to a .ico (Windows) / .icns (macOS) for the executable icon.
    """
    ext = ".exe" if platform.system() == "Windows" else ""
    out = f"{name}{ext}"

    if windowed and platform.system() == "Linux":
        cmd = _gui_spec_cmd(name, script, icon)
    else:
        cmd = [
            sys.executable, "-m", "PyInstaller",
            "--onefile",
            "--name", name,
            "--clean",
            "--noupx",
            "--windowed" if windowed else "--console",
            "--hidden-import=xxhash",
            "--hidden-import=paramiko",
        ]
        # pywin32 powers NTFS owner+DACL preservation (fast_copy imports
        # win32security / pywintypes lazily, so PyInstaller's static scan
        # needs them named explicitly or the ACL copy silently no-ops).
        # NOTE: pip's pywin32 exposes win32* modules as top-level names via
        # pywin32.pth — site-packages/win32 is not an importable package, so
        # --collect-submodules=win32 would collect nothing useful; any new
        # lazy win32 import needs its own --hidden-import here.
        if platform.system() == "Windows":
            cmd += [
                "--hidden-import=win32security",
                "--hidden-import=pywintypes",
            ]
        cmd += cloud_collect_flags()
        if icon and os.path.exists(icon):
            cmd += ["--icon", icon]

        cmd.append(script)

    print(f"\n  Building {out}...")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode == 0:
        binary = os.path.join("dist", out)
        if not os.path.exists(binary):
            # macOS --windowed produces a .app bundle, not a loose file.
            app = os.path.join("dist", f"{name}.app")
            binary = app if os.path.exists(app) else binary
        if os.path.exists(binary):
            size_mb = os.path.getsize(binary) / (1024 * 1024) if os.path.isfile(binary) else 0.0
            print(f"  OK: {binary}" + (f" ({size_mb:.1f} MB)" if size_mb else ""))
        else:
            print(f"  OK: {name} (built)")
        return True
    else:
        print(f"  FAILED: {name}")
        if result.stderr:
            for line in result.stderr.strip().split('\n')[-5:]:
                print(f"    {line}")
        return False


def _find_signtool():
    """Locate signtool.exe — PATH first, then the newest Windows SDK install."""
    from shutil import which
    found = which("signtool")
    if found:
        return found
    import glob
    cands = glob.glob(
        r"C:\Program Files (x86)\Windows Kits\10\bin\*\x64\signtool.exe")
    return sorted(cands)[-1] if cands else None


def sign_binary(path, thumbprint):
    """Authenticode-sign `path` with the cert whose SHA-1 thumbprint is given.
    Timestamps the signature so it stays valid past the cert's expiry. Windows
    only; best-effort (a sign failure never fails the build)."""
    if platform.system() != "Windows":
        print("  signing is Windows-only — skipped")
        return False
    tool = _find_signtool()
    if not tool:
        print("  signtool not found — install the Windows SDK (signtool)")
        return False
    thumb = thumbprint.replace(" ", "")
    cmd = [tool, "sign", "/fd", "SHA256", "/sha1", thumb,
           "/tr", "http://timestamp.digicert.com", "/td", "SHA256", path]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode == 0:
        print(f"  signed: {path}")
        return True
    print(f"  sign FAILED for {path}: {(r.stderr or r.stdout).strip()}")
    return False


def main():
    clean = "--clean" in sys.argv
    sign_thumb = None
    if "--sign" in sys.argv:
        i = sys.argv.index("--sign")
        sign_thumb = sys.argv[i + 1] if i + 1 < len(sys.argv) else None
        # Reject a missing thumbprint OR a following flag ("--sign --clean" must
        # not treat "--clean" as the thumbprint and hand it to signtool /sha1).
        if not sign_thumb or sign_thumb.startswith("-"):
            print("  Error: --sign needs a certificate thumbprint")
            sys.exit(1)

    print(f"Fast Copy Builder - {platform.system()} ({platform.machine()})")
    print("-" * 50)

    if not os.path.exists("fast_copy.py"):
        print("  Error: fast_copy.py not found in current directory")
        sys.exit(1)

    # Install deps
    print("\nDependencies:")
    install_deps()

    # Clean
    if clean:
        for d in ("build", "dist", "__pycache__"):
            if os.path.exists(d):
                shutil.rmtree(d)
        for f in os.listdir("."):
            if f.endswith(".spec"):
                os.remove(f)
        print("\nCleaned build artifacts.")

    # App icon (green bolt): .ico on Windows, .icns on macOS, ignored on Linux.
    icon = None
    if platform.system() == "Windows" and os.path.exists("assets/fast-copy.ico"):
        icon = "assets/fast-copy.ico"
    elif platform.system() == "Darwin" and os.path.exists("assets/fast-copy.icns"):
        icon = "assets/fast-copy.icns"

    # Build
    print("\nBuilding CLI executable...")
    success = build_target("fast_copy", "fast_copy.py", icon=icon)

    # Build the GUI too, when its source is present (skippable via --no-gui).
    gui_src = "fast_copy_modern_gui.py"
    gui_built = False
    if "--no-gui" not in sys.argv and os.path.exists(gui_src):
        print("\nBuilding GUI executable...")
        # Best-effort: a GUI build failure must not sink the required CLI release.
        gui_built = build_target("fast_copy_gui", gui_src, windowed=True, icon=icon)
        if not gui_built:
            print("  WARNING: GUI build failed — continuing with CLI only.")

    # Code-sign the built executables when a cert thumbprint was supplied.
    if sign_thumb and success:
        sext = ".exe" if platform.system() == "Windows" else ""
        print("\nCode-signing...")
        sign_binary(f"dist/fast_copy{sext}", sign_thumb)
        if gui_built:
            sign_binary(f"dist/fast_copy_gui{sext}", sign_thumb)

    # Summary
    ext = ".exe" if platform.system() == "Windows" else ""
    print(f"\n{'-' * 50}")
    if success:
        print(f"Build complete:\n")
        print(f'  dist/fast_copy{ext}')
        if gui_built:
            print(f'  dist/fast_copy_gui{ext}' +
                  ("  (or dist/fast_copy_gui.app on macOS)"
                   if platform.system() == "Darwin" else ""))
        print(f'  Usage: fast_copy "C:\\Source" "E:\\Dest"')
        print(f'         fast_copy /source /dest')
    else:
        print("Build failed.")
    print()


if __name__ == "__main__":
    main()
