#!/usr/bin/env python3
# Copyright 2026 George Kapellakis
# Licensed under the Apache License, Version 2.0
# See LICENSE file for details.
"""
Build script — compiles blitcp into a standalone executable.

Usage:
  python build.py              # build CLI executable
  python build.py --clean      # clean build artifacts first

Output:
  dist/blitcp       — CLI executable
"""

import os
import sys
import shutil
import platform
import importlib.util
import subprocess

# Optional cloud backends. When importable in the build environment they are
# bundled into the frozen binary (see cloud_collect_flags) so the standalone
# GUI/CLI — whose --fc-core engine runs inside the same embedded interpreter —
# can do s3://, az:// and gs:// transfers without a separate Python install.
# Maps the probe-import to the top packages PyInstaller must collect whole
# (these carry data files / metadata that import analysis alone would miss).
CLOUD_COLLECT = {
    "boto3": ["boto3", "botocore", "s3transfer"],
    "azure.storage.blob": ["azure.storage.blob", "azure.core"],
    "google.cloud.storage": ["google.cloud.storage", "google.cloud",
                             "google.api_core", "google.auth",
                             "google.resumable_media"],
    "smbclient": ["smbprotocol", "smbclient", "spnego", "pyasn1"],
}

# Shared libraries the bundle must NOT carry — the host has to provide them.
# Qt's xcb plugin builds its keymap through the host's libxkbcommon-x11, then
# reads it back through libxkbcommon — which the loader resolves to the bundled
# copy. When the two come from different releases their internal keymap structs
# disagree and Qt segfaults inside xkb_state_key_get_layout on the first X key
# event. Leaving them out keeps the host's matched pair intact.
HOST_LIBS = ("libxkbcommon.so", "libxkbcommon-x11.so")

GUI_SPEC_TEMPLATE = '''# -*- mode: python ; coding: utf-8 -*-
# Generated by build.py — do not edit by hand.
import os
from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = [('locales', 'locales')], [], ['xxhash', 'paramiko']
for pkg in {pkgs!r}:
    _d, _b, _h = collect_all(pkg)
    datas += _d
    binaries += _b
    hiddenimports += _h

a = Analysis([{script!r}], binaries=binaries, datas=datas,
             hiddenimports=hiddenimports)

a.binaries = [b for b in a.binaries
              if not os.path.basename(b[0]).startswith({host_libs!r})]

pyz = PYZ(a.pure)
exe = EXE(pyz, a.scripts, a.binaries, a.datas, [],
          name={name!r}, debug=False, strip=False, upx=False,
          runtime_tmpdir=None, console=False, icon={icon!r})
'''


def install_deps():
    """Install build dependencies."""
    deps = {
        "pyinstaller": "PyInstaller",
        "xxhash": "xxhash",
        "paramiko": "paramiko",
        "PySide6": "PySide6",
    }
    for pip_name, import_name in deps.items():
        try:
            __import__(import_name)
            print(f"  OK: {pip_name}")
        except ImportError:
            print(f"  Installing {pip_name}...")
            try:
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install", pip_name, "--quiet",
                    "--disable-pip-version-check",
                ])
            except subprocess.CalledProcessError:
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install", pip_name, "--quiet",
                    "--disable-pip-version-check", "--break-system-packages",
                ])
    # pywin32 is Windows-only and required for NTFS owner/ACL preservation;
    # without it the ACL copy silently no-ops in the frozen binary. Installed
    # from requirements-win.txt (same file CI uses) so the version pin has a
    # single source of truth.
    if platform.system() == "Windows":
        try:
            __import__("win32security")
            print("  OK: pywin32")
        except ImportError:
            print("  Installing pywin32 (requirements-win.txt)...")
            try:
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install", "-r",
                    "requirements-win.txt", "--quiet",
                    "--disable-pip-version-check",
                ])
            except subprocess.CalledProcessError:
                subprocess.check_call([
                    sys.executable, "-m", "pip", "install", "-r",
                    "requirements-win.txt", "--quiet",
                    "--disable-pip-version-check", "--break-system-packages",
                ])
    # Optional cloud SDKs — best-effort so the binary ships with cloud support.
    # A failure here is non-fatal: the build proceeds and simply omits cloud.
    if os.path.exists("requirements-cloud.txt"):
        try:
            __import__("boto3")
            print("  OK: cloud SDKs (boto3/azure/gcs)")
        except ImportError:
            print("  Installing cloud SDKs (boto3/azure/gcs)...")
            for extra in ([], ["--break-system-packages"]):
                try:
                    subprocess.check_call([
                        sys.executable, "-m", "pip", "install", "-r",
                        "requirements-cloud.txt", "--quiet",
                        "--disable-pip-version-check", *extra,
                    ])
                    break
                except subprocess.CalledProcessError:
                    continue
            else:
                print("  WARN: cloud SDKs not installed — binary will omit "
                      "s3://, az:// and gs:// support")


def _cloud_packages():
    """The cloud SDK packages to collect whole, for whichever are importable."""
    collected, seen = [], set()
    for probe, pkgs in CLOUD_COLLECT.items():
        if importlib.util.find_spec(probe) is None:
            continue
        for pkg in pkgs:
            if pkg not in seen:
                seen.add(pkg)
                collected.append(pkg)
    return collected


def cloud_collect_flags():
    """`--collect-all` flags for whichever cloud SDKs are importable here."""
    return ["--collect-all=" + pkg for pkg in _cloud_packages()]


def _gui_spec_cmd(name, script, icon):
    """Build the Linux GUI through a generated .spec, so HOST_LIBS can be kept
    out of the bundle — the PyInstaller CLI offers no way to exclude a binary."""
    spec_path = f"{name}.spec"
    with open(spec_path, "w") as fh:
        fh.write(GUI_SPEC_TEMPLATE.format(
            pkgs=_cloud_packages(),
            script=os.path.abspath(script),
            name=name,
            host_libs=HOST_LIBS,
            icon=os.path.abspath(icon) if icon and os.path.exists(icon) else None,
        ))
    # Only build-time options are legal alongside a .spec; the makespec ones
    # (--onefile, --windowed, --noupx, --icon...) are baked into the spec above.
    return [sys.executable, "-m", "PyInstaller", "--clean", spec_path]


def _mo_write(path, catalog):
    """Write a gettext .mo file (little-endian, no plurals metadata needed
    beyond what the header carries). Pure Python — the gettext CLI tools are
    not a build dependency."""
    import struct
    items = sorted(catalog.items())
    ids = b"".join(k.encode("utf-8") + b"\x00" for k, _ in items)
    strs = b"".join(v.encode("utf-8") + b"\x00" for _, v in items)
    keystart = 7 * 4 + 16 * len(items)
    valuestart = keystart + len(ids)
    koffsets, voffsets, ko, vo = [], [], keystart, valuestart
    for k, v in items:
        kb, vb = k.encode("utf-8"), v.encode("utf-8")
        koffsets.append((len(kb), ko)); ko += len(kb) + 1
        voffsets.append((len(vb), vo)); vo += len(vb) + 1
    out = struct.pack("<7I", 0x950412DE, 0, len(items), 7 * 4,
                      7 * 4 + len(items) * 8, 0, keystart)
    for l, o in koffsets:
        out += struct.pack("<2I", l, o)
    for l, o in voffsets:
        out += struct.pack("<2I", l, o)
    with open(path, "wb") as f:
        f.write(out + ids + strs)


def _po_parse(path):
    """Minimal .po reader: msgid/msgstr pairs with quoted continuation lines.
    Enough for our catalogs; fails loudly on anything unexpected."""
    catalog, cur_id, cur_str, state = {}, None, None, None
    def unesc(s):
        return s.encode().decode("unicode_escape").encode("latin-1").decode("utf-8")
    for ln, raw in enumerate(open(path, encoding="utf-8"), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("msgid "):
            if cur_id is not None:
                catalog[cur_id] = cur_str
            cur_id, cur_str, state = unesc(line[6:].strip().strip('"')), None, "id"
        elif line.startswith("msgstr "):
            cur_str, state = unesc(line[7:].strip().strip('"')), "str"
        elif line.startswith('"'):
            chunk = unesc(line.strip('"'))
            if state == "id":
                cur_id += chunk
            elif state == "str":
                cur_str += chunk
        else:
            raise SystemExit(f"{path}:{ln}: unparseable line: {line!r}")
    if cur_id is not None:
        catalog[cur_id] = cur_str
    missing = [k for k, v in catalog.items() if k and not v]
    if missing:
        raise SystemExit(f"{path}: empty msgstr for: {missing[:3]}")
    return catalog


def compile_locales():
    """locales/<lang>/LC_MESSAGES/blitcp.po → blitcp.mo, with a
    placeholder-consistency check ({name} sets must match, or a translation
    would crash .format() at runtime in that language only)."""
    import re
    n = 0
    for po in sorted(glob_locales := __import__("glob").glob(
            "locales/*/LC_MESSAGES/blitcp.po")):
        catalog = _po_parse(po)
        for k, v in catalog.items():
            if k and set(re.findall(r"{\w*}", k)) != set(re.findall(r"{\w*}", v)):
                raise SystemExit(f"{po}: placeholder mismatch in: {k!r}")
        _mo_write(po[:-3] + ".mo", catalog)
        n += 1
    print(f"  locales: compiled {n} catalogs")
    return n


def build_target(name, script, windowed=False, icon=None):
    """Build a single target with PyInstaller.

    windowed=True builds a GUI app (no console window; a .app bundle on macOS).
    icon is a path to a .ico (Windows) / .icns (macOS) for the executable icon.
    """
    ext = ".exe" if platform.system() == "Windows" else ""
    out = f"{name}{ext}"

    # BLITCP_ONEDIR=1 builds a folder bundle instead of a self-extracting
    # onefile exe. Onefile pays a 16–33s cold-start tax on Windows (unpack to
    # temp + Defender scanning every extracted DLL); onedir starts instantly.
    onedir = bool(os.environ.get("BLITCP_ONEDIR"))
    if windowed and platform.system() == "Linux":
        cmd = _gui_spec_cmd(name, script, icon)
    else:
        cmd = [
            sys.executable, "-m", "PyInstaller",
            "--onedir" if onedir else "--onefile",
            "--name", name,
            "--clean",
            "--noupx",
            "--windowed" if windowed else "--console",
            "--hidden-import=xxhash",
            "--hidden-import=paramiko",
            # Translations (I18N_DESIGN.md): bundled next to the code; the
            # runtime finds them via sys._MEIPASS/locales.
            f"--add-data=locales{os.pathsep}locales",
        ]
        # pywin32 powers NTFS owner+DACL preservation (blitcp imports
        # win32security / pywintypes lazily, so PyInstaller's static scan
        # needs them named explicitly or the ACL copy silently no-ops).
        # NOTE: pip's pywin32 exposes win32* modules as top-level names via
        # pywin32.pth — site-packages/win32 is not an importable package, so
        # --collect-submodules=win32 would collect nothing useful; any new
        # lazy win32 import needs its own --hidden-import here.
        if platform.system() == "Windows":
            cmd += [
                "--hidden-import=win32security",
                "--hidden-import=pywintypes",
            ]
        cmd += cloud_collect_flags()
        if icon and os.path.exists(icon):
            cmd += ["--icon", icon]

        cmd.append(script)

    print(f"\n  Building {out}...")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode == 0:
        binary = os.path.join("dist", out)
        if not os.path.exists(binary):
            # macOS --windowed produces a .app bundle, not a loose file.
            app = os.path.join("dist", f"{name}.app")
            binary = app if os.path.exists(app) else binary
        if os.path.exists(binary):
            size_mb = os.path.getsize(binary) / (1024 * 1024) if os.path.isfile(binary) else 0.0
            print(f"  OK: {binary}" + (f" ({size_mb:.1f} MB)" if size_mb else ""))
        else:
            print(f"  OK: {name} (built)")
        return True
    else:
        print(f"  FAILED: {name}")
        if result.stderr:
            for line in result.stderr.strip().split('\n')[-5:]:
                print(f"    {line}")
        return False


def _find_signtool():
    """Locate signtool.exe — PATH first, then the newest Windows SDK install."""
    from shutil import which
    found = which("signtool")
    if found:
        return found
    import glob
    cands = glob.glob(
        r"C:\Program Files (x86)\Windows Kits\10\bin\*\x64\signtool.exe")
    return sorted(cands)[-1] if cands else None


def sign_binary(path, thumbprint):
    """Authenticode-sign `path` with the cert whose SHA-1 thumbprint is given.
    Timestamps the signature so it stays valid past the cert's expiry. Windows
    only; best-effort (a sign failure never fails the build)."""
    if platform.system() != "Windows":
        print("  signing is Windows-only — skipped")
        return False
    tool = _find_signtool()
    if not tool:
        print("  signtool not found — install the Windows SDK (signtool)")
        return False
    thumb = thumbprint.replace(" ", "")
    cmd = [tool, "sign", "/fd", "SHA256", "/sha1", thumb,
           "/tr", "http://timestamp.digicert.com", "/td", "SHA256", path]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode == 0:
        print(f"  signed: {path}")
        return True
    print(f"  sign FAILED for {path}: {(r.stderr or r.stdout).strip()}")
    return False


def main():
    # Translations first — a bad .po must fail the build, not the user's copy.
    compile_locales()
    clean = "--clean" in sys.argv
    sign_thumb = None
    if "--sign" in sys.argv:
        i = sys.argv.index("--sign")
        sign_thumb = sys.argv[i + 1] if i + 1 < len(sys.argv) else None
        # Reject a missing thumbprint OR a following flag ("--sign --clean" must
        # not treat "--clean" as the thumbprint and hand it to signtool /sha1).
        if not sign_thumb or sign_thumb.startswith("-"):
            print("  Error: --sign needs a certificate thumbprint")
            sys.exit(1)

    print(f"blitcp Builder - {platform.system()} ({platform.machine()})")
    print("-" * 50)

    if not os.path.exists("blitcp.py"):
        print("  Error: blitcp.py not found in current directory")
        sys.exit(1)

    # Install deps
    print("\nDependencies:")
    install_deps()

    # Clean
    if clean:
        for d in ("build", "dist", "__pycache__"):
            if os.path.exists(d):
                shutil.rmtree(d)
        for f in os.listdir("."):
            if f.endswith(".spec"):
                os.remove(f)
        print("\nCleaned build artifacts.")

    # App icon (green bolt): .ico on Windows, .icns on macOS, ignored on Linux.
    icon = None
    if platform.system() == "Windows" and os.path.exists("assets/blitcp.ico"):
        icon = "assets/blitcp.ico"
    elif platform.system() == "Darwin" and os.path.exists("assets/blitcp.icns"):
        icon = "assets/blitcp.icns"

    # Build
    print("\nBuilding CLI executable...")
    success = build_target("blitcp", "blitcp.py", icon=icon)

    # Build the GUI too, when its source is present (skippable via --no-gui).
    gui_src = "blitcp_gui.py"
    gui_built = False
    if "--no-gui" not in sys.argv and os.path.exists(gui_src):
        print("\nBuilding GUI executable...")
        # Best-effort: a GUI build failure must not sink the required CLI release.
        gui_built = build_target("blitcp_gui", gui_src, windowed=True, icon=icon)
        if not gui_built:
            print("  WARNING: GUI build failed — continuing with CLI only.")

    # Code-sign the built executables when a cert thumbprint was supplied.
    if sign_thumb and success:
        sext = ".exe" if platform.system() == "Windows" else ""
        print("\nCode-signing...")
        sign_binary(f"dist/blitcp{sext}", sign_thumb)
        if gui_built:
            sign_binary(f"dist/blitcp_gui{sext}", sign_thumb)

    # Summary
    ext = ".exe" if platform.system() == "Windows" else ""
    print(f"\n{'-' * 50}")
    if success:
        print(f"Build complete:\n")
        print(f'  dist/blitcp{ext}')
        if gui_built:
            print(f'  dist/blitcp_gui{ext}' +
                  ("  (or dist/blitcp_gui.app on macOS)"
                   if platform.system() == "Darwin" else ""))
        print(f'  Usage: blitcp "C:\\Source" "E:\\Dest"')
        print(f'         blitcp /source /dest')
    else:
        print("Build failed.")
    print()


if __name__ == "__main__":
    main()
